Message status
TST-Systems/Voice-of-Time pull request #21
Opened 2023-01-02 12:30 UTC by SalzstangeManga

2023-01-13 12:06 UTC, TLTimeplex requested changes

2023-01-13 12:06 UTC, TLTimeplex commented on VoTCore/Communication/MessageStatus.cs
> +        public bool Status_sent { get => status_sent; }
Warum wechselnde Benennungen? halloWelt / hallo_welt / Hallo_welt ?

2023-01-14 09:56 UTC, TLTimeplex approved these changes

2023-01-17 10:20 UTC, Timkroe21 approved these changes

2023-01-17 10:39 UTC, merged