Create LICENSE
TST-Systems/Voice-of-Time pull request #9
Opened 2022-12-13 19:06 UTC by TLTimeplex

2022-12-17 21:12 UTC, SalzstangeManga approved these changes

2022-12-20 11:51 UTC, Timkroe21 approved these changes

2022-12-20 11:53 UTC, Timkroe21 approved these changes

2022-12-20 11:57 UTC, merged

2022-12-20 12:04 UTC, Timkroe21 requested changes
Die License dürfte von der Formulierung passen